name: Test & Deploy New LiteLLM Version

on:
  workflow_dispatch:
    inputs:
      litellm_version:
        description: 'The litellm version to test, eg. v1.61.0'
        required: true

run-name: Test & Deploy New LiteLLM Version - ${{ inputs.litellm_version }}

jobs:
  test-deploy-cloudrun:
    name: Updating test instance with litellm:${{ inputs.litellm_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Set version info
        run: echo "Testing LiteLLM version ${{ inputs.litellm_version }}"
      
      - uses: actions/checkout@v4
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to litellm test cloud run instance
        run: |
          gcloud run deploy litellm-testing  \
            --image "litellm/litellm:${{ inputs.litellm_version }}" \
            --port 4000 \
            --region ${{ secrets.GCP_LOCATION }} \
            --project ${{ secrets.GCP_PROJECT_ID  }} \
            --service-account ${{ secrets.GCP_PROJECT_SA_NAME }} \
            --set-env-vars STORE_MODEL_IN_DB=false \
            --set-env-vars model_list=${{ secrets.LITELLM_MODEL_LIST }}  \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 1 \
            --concurrency 5 \
            --timeout 500 \
            --execution-environment gen1 \
            --max-instances 10 \
            --allow-unauthenticated \
            --min-instances 1 \
            --ingress all \
            --min 1
      
  run-unit-tests:
    name: Running Unit Tests for litellm:${{ inputs.litellm_version }}
    needs: test-deploy-cloudrun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERVICE_URL: ${{ secrets.LITELLM_TESTING_BASE_URL }}
        run: |
          # Wait for service to be fully available
          ls
          sleep 10
          pytest ./tests/lamatic/test.py -v
  
  deploy-production:
    name: Deploying litellm:${{ inputs.litellm_version }} to production
    runs-on: run-unit-tests
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy litellm-prod  \
            --image "litellm/litellm:${{ inputs.litellm_version }}" \
            --port 4000 \
            --region ${{ secrets.GCP_LOCATION }} \
            --project ${{ secrets.GCP_PROJECT_ID  }} \
            --service-account ${{ secrets.GCP_PROJECT_SA_NAME }} \
            --set-env-vars STORE_MODEL_IN_DB=false \
            --set-env-vars model_list=${{ secrets.LITELLM_MODEL_LIST }}  \
            --memory 512Mi \
            --cpu 2 \
            --min-instances 1 \
            --concurrency 80 \
            --timeout 1000 \
            --execution-environment gen1 \
            --max-instances 100 \
            --allow-unauthenticated \
            --min-instances 1 \
            --ingress all \
            --min 1

  test-production:
    name: Running Unit Tests for litellm:${{ inputs.litellm_version }} on production
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERVICE_URL: ${{ secrets.LITELLM_PROD_BASE_URL }}
        run: |
          # Wait for service to be fully available
          sleep 10
          pytest ./tests/lamatic/test.py -v

  deploy-development:
    name: Deploying litellm:${{ inputs.litellm_version }} to development
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy litellm-dev  \
            --image "litellm/litellm:${{ inputs.litellm_version }}" \
            --port 4000 \
            --region ${{ secrets.GCP_LOCATION }} \
            --project ${{ secrets.GCP_PROJECT_ID  }} \
            --service-account ${{ secrets.GCP_PROJECT_SA_NAME }} \
            --set-env-vars STORE_MODEL_IN_DB=false \
            --set-env-vars model_list=${{ secrets.LITELLM_MODEL_LIST }}  \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 1 \
            --concurrency 10 \
            --timeout 500 \
            --execution-environment gen1 \
            --max-instances 10 \
            --allow-unauthenticated \
            --min-instances 1 \
            --ingress all \
            --min 1

  test-development:
    name: Running Unit Tests for litellm:${{ inputs.litellm_version }} on development
    needs: deploy-development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERVICE_URL: ${{ secrets.LITELLM_DEV_BASE_URL }}
        run: |
          # Wait for service to be fully available
          sleep 10
          pytest ./tests/lamatic/test.py -v

      